name: MTunes
version: ${project.version}
main: mtunes.MTunes
commands:
   soundtest:
      description: This is a demo command.
      usage: /<command> [player]
      permission: tutorialplugin.basic
      permission-message: You don't have <permission>